# Use official PostgreSQL image
FROM postgres:latest

# Set environment variables used in prisma service
ENV POSTGRES_DB=db
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=pass

# Expose the PostgreSQL port
EXPOSE 5432